/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.sample.employee.controller;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.sample.employee.model.EmployeeDetails;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-11-21T05:47:53.676Z")

@Api(value = "employees", description = "the employees API")
public interface EmployeesApi {
	
	@ApiOperation(value = "Register a  employyee", nickname = "EmployeeRegistration", notes = "", tags={ "Employee-Details", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/employee/registration",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addEmloyee(@ApiParam(value = "Employee object that needs to be added to the store" ,required=true )  @Valid @RequestBody EmployeeDetails body);


    @ApiOperation(value = "Find All employees", nickname = "getEmployees", notes = "Returns a all Employees", response = EmployeeDetails.class, responseContainer = "List", tags={ "Employee-Details", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = EmployeeDetails.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Employees not found") })
    @RequestMapping(value = "/employeesRecords",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<EmployeeDetails>> getEmployees();
    
    

}
